meta_product_name: "Conscious Clicks"
meta_title: "Concsious Clicks- change your online habits"
meta_description: "A magical antidote to digital brainwashing"
meta_image: "blue-mountains.jpg" # should exist in `app/assets/images/`

